services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ModuloProductos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 ModuloProductos.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db/ModuloProductos
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
