services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ModuloProductos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

  web:
    build:
      context: .
      labels:
        - "project=ModuloProductos"
    command: >
      bash -c "python manage.py migrate && 
               python manage.py import_segmento &&
               gunicorn --bind 0.0.0.0:8000 ModuloProductos.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:1234@db/ModuloProductos
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: always

volumes:
  postgres_data:

networks:
  app_network:
