# Generated by Django 5.1 on 2024-09-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo05TiposTributos',
            fields=[
                ('codigo', models.CharField(db_column='Codigo', max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Name', max_length=6, null=True)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
                ('un_ece_5153', models.CharField(blank=True, db_column='UN_ECE_5153', max_length=3, null=True)),
                ('un_ece_5305', models.CharField(blank=True, db_column='UN_ECE_5305', max_length=1, null=True)),
            ],
            options={
                'db_table': 'CATALOGO_05_TIPOS_TRIBUTOS',
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'familia_producto',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(max_length=200, null=True)),
                ('valorUnitario', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('peso', models.FloatField(null=True)),
                ('volumen', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoProducto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'segmento_producto',
            },
        ),
        migrations.CreateModel(
            name='TipoPrecio',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_precio',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='ClaseProducto',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.familiaproducto')),
            ],
            options={
                'db_table': 'clase_producto',
            },
        ),
        migrations.CreateModel(
            name='ItemImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.catalogo05tipostributos')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.claseproducto')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='codigoProducto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto'),
        ),
        migrations.AddField(
            model_name='familiaproducto',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.segmentoproducto'),
        ),
        migrations.AddField(
            model_name='item',
            name='tipoPrecio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoprecio'),
        ),
        migrations.AddField(
            model_name='item',
            name='unidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidadmedida'),
        ),
    ]
