# Generated by Django 4.2.16 on 2024-10-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_item_imagen_item_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo05tipostributos',
            name='un_ece_5153',
            field=models.CharField(blank=True, db_column='UN_ECE_5153', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='catalogo05tipostributos',
            name='un_ece_5305',
            field=models.CharField(blank=True, db_column='UN_ECE_5305', max_length=5, null=True),
        ),
    ]
