# Generated by Django 4.2.16 on 2024-11-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_catalogo07tiposdeafectaciondeligv_conjunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigoBarras',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
