# Generated by Django 4.2.16 on 2024-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_codigobarras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='valorUnitario',
            field=models.FloatField(),
        ),
    ]
