name: Django Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2 instance
        run: |
          scp -o StrictHostKeyChecking=no -r * ec2-user@${{ secrets.EC2_IP }}:/home/ec2-user/projects/Qickart/${{ secrets.SERVICE_NAME }}

      - name: Connect to EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ec2-user/projects/Qickart/${{ secrets.SERVICE_NAME }}
          
          # Remove the corrupted docker-compose if it exists
          sudo rm -f /usr/local/bin/docker-compose
          
          # Install docker-compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          
          # Stop and remove old containers
          docker-compose down --remove-orphans
          
          # Prune unused images and volumes for this specific project
          docker image prune -f --filter "label=project=${{ secrets.SERVICE_NAME }}"
          docker volume ls -q --filter "label=project=${{ secrets.SERVICE_NAME }}" | xargs -r docker volume rm
          
          # Build and start containers
          docker-compose up -d --build --no-recreate db
          docker-compose up -d --build web
          exit
          EOF
